# Generated by Django 3.0.5 on 2020-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'ON PROGRESS'), ('RE', 'REVIEWING'), ('FU', 'FOLLOW UP'), ('CP', 'COMPLETED')], default='OP', max_length=2),
        ),
    ]
