# Generated by Django 3.0.5 on 2020-10-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_members',
        ),
    ]
