# Generated by Django 3.0.5 on 2020-10-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_task_task_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_members',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
